version: "3.9"
services:
  zookeeper:
    image: debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    cpus: "0.5"
    mem_reservation: 100M
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: 50m
  kafka:
    image: debezium/kafka
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=DOCKER_INTERNAL://0.0.0.0:29092,DOCKER_EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - ZOOKEEPER_CONNECT=zookeeper:2181
    cpus: "0.5"
    mem_reservation: 100M
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: 50m
  connect:
    image: debezium/connect
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=G1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - zookeeper
      - kafka
    cpus: "0.5"
    mem_reservation: 100M
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: 50m
  db:
    image: debezium/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    cpus: "0.5"
    mem_reservation: 100M
    mem_limit: 512M
    logging:
      driver: json-file
      options:
        max-size: 50m